<?php
namespace app\admin\controller;
use app\admin\controller\base\Backend;

class Feedback extends Backend
{
    public $model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\model\Feedback();
    }

    // 建议反馈列表
    public function index() {
        $list = $this->model->order(['id' => 'desc'])->paginate();
        return view('', [
            'list' => $list
        ]);
    }

    public function detail() {
        $id = input('id', 0);
        $feedback = $this->model->where('id', $id)->find();
        return view('', [
            'feedback' => $feedback
        ]);
    }
}