<?php
// 联赛
namespace app\admin\controller;
use app\admin\controller\base\Backend;
use app\model\Match;
use app\model\MatchOrg;

class League extends Backend
{
    public $model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new Match();
    }

    // 联赛列表
    public function index() {
        $map['match_org_id'] = ['<>', 0];
        $list = $this->model->where($map)->order(['status' => 'asc', 'id' => 'desc'])->paginate();

        return view('', [
            'list' => $list
        ]);
    }

    // 联赛详情
    public function detail() {
        $id = input('id', 0, 'intval');
        $matchInfo = $this->model->with('MatchOrg')->where(['id' => $id])->find();
        dump($matchInfo->toArray());

        return view('', [
            'matchInfo' => $matchInfo
        ]);
    }

    // 审核联赛
    public function audit() {

    }
}