<?php 
namespace app\mall\controller;
use app\common\controller\Frontend;

class Base extends Frontend {
	public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
	}



}
