<?php
namespace app\frontend\controller;
use app\service\CampService;

class Financial extends Base {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $camp_id = input('param.camp_id');
        $campS = new CampService();
        $campInfo = $campS->getCampInfo($camp_id);
        $this->assign('campInfo', $campInfo);
        $this->assign('camp_id', $camp_id);
    }

    public function billlist() {
        return view('Financial/billlist');
    }

    public function statistics() {
        return view('Financial/statistics');
    }
}