<?php
namespace app\frontend\controller;
use app\service\CampService;

class Financial extends Base {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $camp_id = input('param.camp_id');
        $campS = new CampService();
        $campInfo = $campS->getCampInfo($camp_id);
        $this->assign('campInfo', $campInfo);
        $this->assign('camp_id', $camp_id);
    }

    public function billlist() {
        return view('Financial/billlist');
    }

    // 训练营财务统计
    public function statistics() {
        // 初始化时间选择器日期（年、月、上月、本月第一天、本月最后一天）
        $dateTime = initDateTime();


        $this->assign('dateTime', $dateTime);
        return view('Financial/statistics');
    }
}