<?php
// 球队模块
namespace app\frontend\controller;


use app\service\TeamService;

class Team extends Base {
    public $team_id;
    public $teamInfo;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 获取球队详细信息 模块下全局赋值
        $team_id = input('team_id');
        $teamS = new TeamService();
        $teamInfo = $teamS->getTeam(['id' => $team_id]);
        $this->team_id = $team_id;
        $this->teamInfo = $teamInfo;
        $this->assign('team_id', $team_id);
        $this->assign('teamInfo', $teamInfo);
    }

    // 球队列表(平台展示)
    public function teamlist() {
        return view('Team/teamList');
    }

    // 创建球队
    public function createteam() {
        return view('Team/createTeam');
    }

    // 球队管理
    public function teammanage() {
        // 获取会员在球队角色身份
        $checkMemberTeamRoleMap = ['team_id' => $this->team_id, 'member_id' => $this->memberInfo['id']];
        $teamS = new TeamService();
        $teamrole = $teamS->checkMemberTeamRole($checkMemberTeamRoleMap);
        //dump($teamrole);
        $this->assign('teamrole', $teamrole);
        return view('Team/teamManage');
    }

    // 编辑球队
    public function teamedit() {
        // 获取球队有角色身份的会员列表
        $teamS = new TeamService();
        $rolemembers = $teamS->getTeamRoleMembers($this->team_id);
        //dump($rolemembers);
        $this->assign('rolemembers', $rolemembers);
        return view('Team/teamEdit');
    }

    // 球队首页
    public function teaminfo() {
        // 球队胜率输出
        $this->teamInfo['win_rate'] = 0;
        if ($this->teamInfo['match_num']) {
            if ($this->teamInfo['match_win']) {
                $winrate = ($this->teamInfo['match_win']/$this->teamInfo['match_num']);
                $winrate = sprintf("%.2f", $winrate);
                $this->teamInfo['win_rate'] = $winrate*100;
            }  else {
                $this->teamInfo['win_rate'] = 0;
            }
        }
        return view('Team/teamInfo');
    }

    // 我的球队列表（会员加入/所在球队列表）
    public function myteam() {
        return view('Team/myteam');
    }

    // 队员列表
    public function teammember() {
        return view('Team/teamMember');
    }

    // 队员档案
    public function teammemberinfo() {
        // 接收参数
        $team_id = input('team_id', 0);
        $member_id = input('member_id', 0);
        $teamS = new TeamService();
        // 获取队员在当前球队的数据信息
        $map = ['team_id' => $team_id, 'member_id' => $member_id];
        $teamMemberInfo = $teamS->getTeamMemberInfo($map);

        // 该队员的其他球队列表
        $memberOtherTeamMap = [ 'member_id' => $member_id, 'team_id' => ['neq', $team_id]];
        $memberOtherTeam = $teamS->getTeamMemberList($memberOtherTeamMap);

        $this->assign('teamMemberInfo', $teamMemberInfo);
        $this->assign('memberOtherTeam', $memberOtherTeam);
        return view('Team/teamMemberInfo');
    }

    // 粉丝列表
    public function fans() {
        return view('Team/fans');
    }

    // 消息列表
    public function messagelist() {
        return view('Team/messagelist');
    }

    // 消息详情
    public function messageinfo() {
        return view('Team/messageInfo');
    }

    // 发布球队消息（公告）
    public function createmessage() {
        return view('Team/createMessage');
    }

    // 相册列表
    public function album() {
        return view('Team/album');
    }

    // 比赛列表（球队参与的）
    public function competition() {
        return view('Team/competition');
    }

    // 活动列表
    public function eventlist() {
        return view('Team/eventList');
    }

    // 活动详情
    public function eventInfo() {
        return view('Team/eventInfo');
    }

    // 活动报名

    // 活动报名人员名单

    // 创建活动

    // 编辑活动

    // 活动录入


}